In [3]:
import numpy as np
import torch

# [Temp, Rain, Humidity]
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype = 'float32')


# [Apples]
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs)
print(targets)


w = torch.randn(3, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(w)
print(b)

def model(x):
    return x @ w + b
  
preds = model(inputs)
print(preds)
print(targets)

# Loss Function
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

loss = mse(preds, targets)
print(loss)
loss.backward()

print(w)
print(w.grad)
print(b)
print(b.grad)

w.grad.zero_()
b.grad.zero_()

print(w.grad)
print(b.grad)

preds = model(inputs)
print(preds)

loss = mse(preds, targets)
print(loss)

print(w.grad)
print(b.grad)

with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

print(w)
print(b)

preds = model(inputs)
loss = mse(preds, targets)
print(loss)

for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

preds = model(inputs)
loss = mse(preds, targets)
print(loss)
preds
targets

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
tensor([[ 0.1730],
        [-0.8926],
        [-0.0290]], requires_grad=True)
tensor([0.6993], requires_grad=True)
tensor([[ -47.7210],
        [ -63.9603],
        [-105.5381],
        [ -21.1064],
        [ -75.0820]], grad_fn=<AddBackward0>)
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
tensor(23152.0449, grad_fn=<DivBackward0>)
tensor([[ 0.1730],
        [-0.8926],
        [-0.0290]], requires_grad=True)
tensor([[-22792.9355],
        [-27497.3438],
        [-16328.5371]])
tensor([0.6993], requires_grad=True)
tensor([-277.7631])
tensor([[0.],
        [0.],
        [0.]])
tensor([0.])
tensor([[ -47.7210],
        [ -63.9603],
        [-105.5381],
        [ -21.1064],
        [ -75.0820]], grad_fn=<AddBackward0>)
tensor(23152.0449,

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])